### ISSUE TITLE
is there any information about how to use maxinet with opendaylight?

### ISSUE THREAD

**Issue by bmullan** [MaxiNet/MaxiNet#10]
I'd used ODL with mininet before but are their any special configuration required to use ODL with Maxinet?

**Comment by schwabe** [comment]
No, no special configuration. You use a RemoteController like you would do in MiniNet.

**Comment by bmullan** [comment]
Does that mean each server you have to configure external controller IP.
?   Wouldn't it be better for all mininets to be registered (somehow) with
maxinet then maxinet ID the sdn controller ?

**Comment by schwabe** [comment]
No, you configure the controller once and MaxiNet configures the switches that they connect to that controller. Basically, like MiniNet but MaxiNet does the distribution of the switches etc.

**Comment by wallaschek** [comment]
Sidenote: You can configure the external controller IP in the MaxiNet.cfg (controller entry). You need to configure this on the machine that hosts the frontendserver, then it will automatically be used by all workers which connect to that frontendserver.

**Comment by bmullan** [comment]
Felix

ah, I thought there might be something like that cfg entry somewhere.

thanks.
brian
