### ISSUE TITLE
Topology not setting up

### ISSUE THREAD

**Issue by ChaitanyaKr** [MaxiNet/MaxiNet#11]
Hi,
I attempted a topology, using the examples in the MaxiNet repository as a reference. For my purpose, I put up about 15 switches, each on a worker VM. 

Firstly, I wasn't able to get all of them to sign in too. So, I reduced them to 14, and all 14 could sign in at the FrontEndServer. 
However, when I run the topology script at the front end, it gets stuck at the following line and nothing happens:
`cluster = maxinet.Cluster(minWorkers=14, maxWorkers=14)`

Any ideas as to what could be going wrong here?

The topology code is attached.
[Maxinet_Topo_v5_1.txt](https://github.com/MaxiNet/MaxiNet/files/276220/Maxinet_Topo_v5_1.txt)

**Comment by wallaschek** [comment]
Have you tried enabling debug mode according to https://github.com/MaxiNet/MaxiNet/wiki/Debugging-MaxiNet ? Any interesting output on one of the servers?
