### ISSUE TITLE
running MaxiNet on python 2.7.10

### ISSUE THREAD

**Issue by stevelorenz** [MaxiNet/MaxiNet#12]
Hello,

I'm using MaxiNet for a study project. I want to create a cluster of 16 Odroids(a single board computer like Raspberry pi) with Ubuntu 15.10(default latest image). And I have tested my program on virtual machine with Ubuntu14.04 and python 2.7.6, everything is fine. But on Odroid with python 2.7.10 it doesn't work. It seems some mistake with Pyro function changes. Can MaxiNet be updated to support latest Version of modules? Thank you very much for the help.

Zuo Xiang

**Comment by schwabe** [comment]
What problem are you exactly seeing?

**Comment by stevelorenz** [comment]
Thanks schwabe. I do not have the device today at home , tomorrow i will get the detailed error info and post it.

**Comment by stevelorenz** [comment]
Hello Schwabe,

Today i try to use the latest mirror-list , remove all and install again, and this time MaxiNet works... Maybe something wrong with the last installation. MaxiNet is a very good tool for my work and thanks so much.

Have a nice day
