### ISSUE TITLE
TCP/UDP Not Working unless I use OVSSwitch

### ISSUE THREAD

**Issue by mvanotti** [MaxiNet/MaxiNet#15]
Hi!

I was playing around with MaxiNet, and got stuck for a long time trying to get an app running. I started by modifying the basic ping example.

I tried to run basic tcp and udp programs, netcat, etc, but I was not able to do so. Just before giving up, I noticed the sshd example, and tried it out. It worked.

I noticed that the only change I had to do to my code was to add switch=OVSSwitch on experiment creation.

Is this documented somewhere? are there any other caveats I am not aware of? (All the things I tried worked with mininet out of the box). It would be nice to have tcp enabled by default, or an explanation on how to enable it.

**Comment by wallaschek** [comment]
MaxiNet should also work with the userspace reference implementation, openvswitch is not a requirement. Did the original basic ping example work for you?

**Comment by mvanotti** [comment]
Hi! Thanks for the answer.

ping/arp works without problem, but as soon as I want to run something over tcp/udp it doesn't work.

Maybe MaxiNet should not change the default switch to UserSpaceSwitch, and leave the same default as MiniNet.

**Comment by wallaschek** [comment]
Have you checked your network interface MTU? See https://github.com/MaxiNet/MaxiNet/wiki/FAQ#A-ping-between-any-two-host-pairs-works-well-but-using-iperf-i-observe-very-low-data-rates

**Comment by mvanotti** [comment]
I don't think that was the problem.
Maybe there was a problem with my computer and that switch, but I think it should default to the same as mininet.
Changing the switch made it work, and if I enabled the use1500MTU option it still didn't work.

**Comment by wallaschek** [comment]
I'm closing this for now. The userspace switch implementation was chosen as default as openvswitch sometimes behaves strangely if simulating a lot of switches on the same host, while the userspace implementation is subject to the default linux scheduler. I'm still convinced that your original problem is somewhat MTU related as it is exactly the same behaviour one can observe when using a switch that does not support MTUs greater than 1500.

**Comment by mvanotti** [comment]
But if I change the switch it works.. And I was running it with a peer to peer connection.. Just a normal switch with normal computers... When I changed the switch it started working..

**Comment by schwabe** [comment]
@mvanotti try debugging your problem with wireshark
