### ISSUE TITLE
dilation factor

### ISSUE THREAD

**Issue by cheersa** [MaxiNet/MaxiNet#16]
Hi,
It is able to set on the experiment of performance evaluation of paper.
With finding all files, I can't find where I can set dilation factor.
Does not variable of dilation factor exist?

The name of paper is "MaxiNet: Distributed emulation of software-defined networks"
Thank you,

**Comment by schwabe** [comment]
The dillation factor is something you need to for own experiment e.g. scale all data rates down by your dillation factor and increase all times by the dillation factor.
