### ISSUE TITLE
Pyro4.errors.ConnectionClosedError

### ISSUE THREAD

**Issue by stevelorenz** [MaxiNet/MaxiNet#18]
Hello,

sorry that i have problems again. When i run experiments on MaxiNet cluster(some link parameter mesurements, like bandwidth test with Iperf), normally everything works fine. But sometime following error takes place randomly, especilly by some tests, that take relative long(1-2 days) emulation time. 
```
Pyro4.errors.ConnectionClosedError: receiving: connection lost: [Errno 113] No route to host
```
And the Experiment stoped, but some workers still attached to the tests and i need to reboot all workers to run measurements again. That is a problem for me.

The detailed error information is in following txt file. I haven't used Pyro before. So maybe there is a solution to solve this annoying problem. Thanks so much for the help.

[error_log.txt](https://github.com/MaxiNet/MaxiNet/files/409026/error_log.txt)

**Comment by schwabe** [comment]
That sounds like some intermediate network problem between the frontend and the worker. Can you your network setup?

**Comment by stevelorenz** [comment]
For the test i use a cluster of 16 odroid-workers and one central controller, all of these single board computers are connected to a switch and using static ips, controlled by NetWorkManager for default Ethernet interface. What do you mean by setup the network?

**Comment by schwabe** [comment]
The error messages indicate a problem with the network setup. In our experience NetworkManager has only lead to problems and we ended up unistalling networkmanager and configuring the network with /etc/network/interfaces.

**Comment by stevelorenz** [comment]
Ach so! At the beginning, I also tried to setup the interface in /etc. But there is a annoying problem for these odroids: they change MAC address and interface name sometime after boot. So the static settings do not work... So that leads me to use NetworkManager to bind static ip to all MAC address(leer option in MAC address)... Maybe i should find a method to deal with these odroids to allow setup in /etc/network/interfaces. Thanks so much for the help.

**Comment by schwabe** [comment]
Changing mac addresses inteface in regular intervals sounds very bad. Probably while this happens the connection to the network is disrupted (your no route message).

**Comment by stevelorenz** [comment]
And another small question, if the MaxiNet also provide a mininet like net object for users to choose host and switch type? like CPULimitedHost and OVSwitch etc.

**Comment by schwabe** [comment]
@stevelorenz @wallaschek already answered that in #17

**Comment by stevelorenz** [comment]
Thanks so much for your help.
