### ISSUE TITLE
MaxiNet not working with 1500 MTU

### ISSUE THREAD

**Issue by mvanotti** [MaxiNet/MaxiNet#19]
Hi!

I was just testing MaxiNet over an ethernet connection with 1500 MTU and I could not get it working. I just couldn't create any TCP connection between any pair of nodes (ping works perfectly for any packet size). I've tried with **runWith1500MTU = True** and still doesn't work.

Some of the maxinet examples (dynamic topos) don't work either: I can't even run ping with manually added nodes.

**Comment by mvanotti** [comment]
Each of the machines has two interfaces, one with > 2000 MTU and one with 1500 MTU. If I use the one with 2000 MTU everything works perfectly, but with the one with 1500 MTU it just doesn't work :(.

**Comment by schwabe** [comment]
Can you try to diagnose the problem with tcpdump to see if maxinet really lowers the mtu of its interfaces. Also doing ifconfig and checking the mtu of the virtual interfaces. Should be 1400.

**Comment by schwabe** [comment]
No response from submitter
