### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by MaralAfris** [MaxiNet/MaxiNet#24]
Hi,

I am running MaxiNet on Ubuntu 16.10 (using a virtual machine from parallels). Installed from the latest install.sh, everything went fine.

It seems that starting the worker 1 as in the tutorial it worked fine (no message, no error).
> screen -d -m -S MaxiNetFrontend MaxiNetFrontendServer
> screen -d -m -S MaxiNetWorker sudo MaxiNetWorker

But when I run MaxiNetStatus I got:
> user@ubuntu:~/MaxiNet/MaxiNet/Frontend/examples$ MaxiNetStatus
> Traceback (most recent call last):
>   File "/usr/local/bin/MaxiNetStatus", line 11, in <module>
>     load_entry_point('MaxiNet==1.1', 'console_scripts', 'MaxiNetStatus')()
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/WorkerServer/server.py", line 395, in getFrontendStatus
>     config = MaxiNetConfig(register=False)
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/tools.py", line 30, in __init__
>     self.set_loglevel()
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/tools.py", line 37, in set_loglevel
>     level = self.get_loglevel()
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/tools.py", line 104, in get_loglevel
>     lvl = self.get("all", "logLevel")
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/tools.py", line 133, in get
>     return RawConfigParser.get(self, section, option)
>   File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
>     raise NoSectionError(section)
> ConfigParser.NoSectionError: No section: 'all'

Any idea where this can come from ? May be something silly

**Comment by schwabe** [comment]
That sounds lie your config has no [all] section. See the example config

**Comment by MaralAfris** [comment]
Ok, I'll look into that then. Thx !

**Comment by ChengHuangUCAS** [comment]
It's four years later... Well, anyway, It seems you didn't put the config file in proper dir with a right name. Something like [this](https://github.com/MaxiNet/MaxiNet/blob/f02524ad131fb0464e35e35a05c5b6d1a457cf8d/MaxiNet/tools.py#L28) needs.
