### ISSUE TITLE
tools.makeMAC() should not return a multicast address

### ISSUE THREAD

**Issue by osearbhain** [MaxiNet/MaxiNet#26]
tools.makeMAC() appears to be intended to generate a unicast MAC address that is probably unique on a network, and that can be assigned to a host e.g. like this:
&nbsp;&nbsp;topo.addHost("h1", ip=Tools.makeIP(1), mac=Tools.makeMAC(1))

However, tools.makeMAC() should check that the left-most octet is even before the generated address is returned, since bit 1 of that octet indicates whether the MAC address is unicast or multicast. If it is multicast (bit 1 of left-most octet has a value of 1), a host will not accept the address for assignment to a NIC.

**Comment by schwabe** [comment]
Thanks for the report!

**Comment by mvanotti** [comment]
You are not calling the right function I believe.

you have modified randByte from FatTreeTopo, which doesn't have this problem, [fixed here](https://github.com/MaxiNet/MaxiNet/pull/20/commits/3271bd8b2a9c0b3e2d5afa6f8d9fdf9522c67737)

However, I missed the Tools.makeMac function, which should be fixed too. Also, both functions should be consistent.
