### ISSUE TITLE
Q: is there a way maxinet can be packaged as a docker image rather than a vm?

### ISSUE THREAD

**Issue by yogeshVU** [MaxiNet/MaxiNet#27]
Q: is there a way maxinet can be packaged as a docker image rather than a vm?

**Comment by schwabe** [comment]
Probably not without massive problems as maxinet and docker use virtual name spaces.

**Comment by markgoddard** [comment]
You could try running it with --net=host to execute in the host's namespace.

Mark

**Comment by yogeshVU** [comment]
Looks like there is a docker image for maxinet. Anyone used this one?
https://hub.docker.com/r/wette/maxinet/
