### ISSUE TITLE
 MaxiNet1.2  runs normally on a single machine, but runs error on multiple machines

### ISSUE THREAD

**Issue by yyqdh** [MaxiNet/MaxiNet#35]
MaxiNet1.2  runs normally on a single machine, but runs error on multiple machines.I'm not sure whether the installation is wrong or the configuration is wrong. 
I installed  MaxiNet1.2 on the mininet2.2.1 vm provided by  mininet Official website. No errors were found during installation.I am running the frontendserver and the worker on one vm. And simplePing.py programs can be run successfully.However when I used two vm ,one(maxinet10) used as "frontendserver", another(maxinet11) used as "work", simplePing.py programs can be run successfully
I have two VM where I am running the fronendserver and the worker.The following errors occurred when the program was running:
mininet@maxinet11:~$ /usr/local/share/MaxiNet/examples/simplePing.py

localhost SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
localhost SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
```
no hostkey alg
Traceback (most recent call last):
  File "/usr/local/share/MaxiNet/examples/simplePing.py", line 14, in <module>
    cluster = maxinet.Cluster()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 611, in __init__
    self.add_workers()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 705, in add_workers
    while self.add_worker():
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 690, in add_worker
    if(self.add_worker_by_hostname(hn)):
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 669, in add_worker_by_hostname
    self.worker.append(Worker(self.nameserver, pyname, self.config.get_nameserver_password(), self.sshtool))
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 136, in __init__
    self._fix_mtus()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 344, in _fix_mtus
    self.run_cmd("ip li se dev " + intf + " mtu 1600")
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 271, in run_cmd
    return self.server.check_output(cmd)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 187, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 463, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/util.py", line 170, in deserializeData
    return self.loads(data)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/util.py", line 451, in loads
    return pickle.loads(data)
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())
```

```
mininet@maxinet11:~$ 
==============================
Last login: Wed Nov 22 06:36:26 2017
mininet@maxinet10:~$  MaxiNetFrontendServer
Broadcast server running on 0.0.0.0:9091
NS running on 192.168.10.10:9090 (192.168.10.10)
URI = PYRO:Pyro.NameServer@192.168.10.10:9090
Monitoring clusters...
INFO:MaxiNet.FrontendServer.server:startup successful. Waiting for workers to register...
INFO:MaxiNet.FrontendServer.server:new worker signed in: maxinet11 (pyro: MaxiNetWorker_maxinet11)
INFO:MaxiNet.FrontendServer.server:reserved worker maxinet11 for id maxinet11:/usr/local/share/MaxiNet/examples/simplePing.py
WARNING:MaxiNet.FrontendServer.server:Detected a hung cluster. Freeing workers.
INFO:MaxiNet.FrontendServer.server:worker maxinet11 was freed
INFO:MaxiNet.FrontendServer.server:reserved worker maxinet11 for id maxinet11:/usr/local/share/MaxiNet/examples/simplePing.py
WARNING:MaxiNet.FrontendServer.server:Detected a hung cluster. Freeing workers.
INFO:MaxiNet.FrontendServer.server:worker maxinet11 was freed
=====================================================================
mininet@maxinet11:~$  sudo MaxiNetWorker
INFO:MaxiNet.WorkerServer.server:starting up and connecting to  192.168.10.10:9090
INFO:MaxiNet.WorkerServer.server:configuring and starting ssh daemon...
INFO:MaxiNet.WorkerServer.server:looking for manager application...
INFO:MaxiNet.WorkerServer.server:signing in...
INFO:MaxiNet.WorkerServer.server:done. Entering requestloop.
===============================================================
```

 My MaxiNet.cfg  file reads as follows:

```
; place this at ~/.MaxiNet.cfg
[all]
password = HalloWelt
controller = 192.168.10.1.1:6633
logLevel = INFO        ; Either CRITICAL, ERROR, WARNING, INFO  or DEBUG
port_ns = 9090         ; Nameserver port
port_sshd = 5345       ; Port where MaxiNet will start an ssh server on each worker
runWith1500MTU = False ; Set this to True if your physical network can not handle MTUs >1500.
useMultipleIPs = 0     ; for RSS load balancing. Set to n > 0 to use multiple IP addresses per worker. More information on this feature can be found at MaxiNets github Wiki.
deactivateTSO = True   ; Deactivate TCP-Segmentation-Offloading at the emulated hosts.
sshuser = mininet         ; On Debian set this to root. On ubuntu set this to user which can do passwordless sudo
usesudo = True        ; If sshuser is set to something different than root set this to True.
useSTT = False         ; enables stt usage for tunnels. Only usable with OpenVSwitch. Bandwithlimitations etc do not work on STT tunnels!

[FrontendServer]
ip = 192.168.10.10
threadpool = 256       ; increase if more workers are needed (each Worker requires 2 threads on the FrontendServer)

[maxinet11]
ip = 192.168.10.11
share = 1

```

**Comment by mpeuster** [comment]
Hi,

not sure how the Mininet VM is configured. But it might be a much better idea to start with fresh Ubuntu 14.04 or 16.04 VMs and configure them according to: https://maxinet.github.io/#installation

Especially the password-less `sudo` is important here.

After that you could use MaxiNets installation script to install MaxiNet together with Mininet in a single step.

**Comment by yyqdh** [comment]
Is the above error caused by the configuration of pyro4?Thank you for your advice.I'm trying to install it from fresh UBUNTU 14.04 VM. It will take me some time.
In addition, the MaxiNet-1.0-rc1.ova provided on the official website can not  correctly import VMware Workstation 12  and virbox 5.2.Can you provide an updated version of the VM file（MaxiNet-1.2）?

**Comment by mpeuster** [comment]
Sorry we are currently not able to update the VM image. We recommend the installation using the install script. Since this is the tested way of deployment.

**Comment by kalcla** [comment]
Hi everybody,
I installed Maxinet with a fresh Ubuntu 14.04 and using installer.sh ver. 2, but I have the same problem.
I used two vm too ,one used as "frontendserver" and "worker", another used as "worker".
If I launch simpleping.py all right, but when I launch static_mapping.py I have many errors.

Frontendserver

> Broadcast server running on 0.0.0.0:9091
NS running on 192.168.1.124:9090 (192.168.1.124)
URI = PYRO:Pyro.NameServer@192.168.1.124:9090
Monitoring clusters...
DEBUG:MaxiNet.FrontendServer.server:starting up and connecting to  192.168.1.124:9090
INFO:MaxiNet.FrontendServer.server:startup successful. Waiting for workers to register...
INFO:MaxiNet.FrontendServer.server:new worker signed in: wubuntu01 (pyro: MaxiNetWorker_wubuntu01)
INFO:MaxiNet.FrontendServer.server:new worker signed in: wubuntu02 (pyro: MaxiNetWorker_wubuntu02)
INFO:MaxiNet.FrontendServer.server:reserved worker wubuntu02 for id wubuntu01:static_mapping.py
INFO:MaxiNet.FrontendServer.server:reserved worker wubuntu01 for id wubuntu01:static_mapping.py
INFO:MaxiNet.FrontendServer.server:worker wubuntu02 was freed
INFO:MaxiNet.FrontendServer.server:worker wubuntu01 was freed


Worker 1
> INFO:MaxiNet.WorkerServer.server:starting up and connecting to  192.168.1.124:9090
> INFO:MaxiNet.WorkerServer.server:configuring and starting ssh daemon...
> INFO:MaxiNet.WorkerServer.server:looking for manager application...
> INFO:MaxiNet.WorkerServer.server:signing in...
> INFO:MaxiNet.WorkerServer.server:done. Entering requestloop.
> DEBUG:MaxiNet.WorkerServer.server:Executing /usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Scripts/load_tunneling.sh
> DEBUG:MaxiNet.WorkerServer.server:Executing /usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Scripts/create_tunnel.sh 192.168.1.124 192.168.1.125 mn_tun0 0
> DEBUG:MaxiNet.WorkerServer.server:Executing /usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Scripts/delete_tunnels.sh

Worker 2
> INFO:MaxiNet.WorkerServer.server:starting up and connecting to  192.168.1.124:9090
INFO:MaxiNet.WorkerServer.server:configuring and starting ssh daemon...
INFO:MaxiNet.WorkerServer.server:looking for manager application...
INFO:MaxiNet.WorkerServer.server:signing in...
INFO:MaxiNet.WorkerServer.server:done. Entering requestloop.
DEBUG:MaxiNet.WorkerServer.server:Executing /usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Scripts/load_tunneling.sh
DEBUG:MaxiNet.WorkerServer.server:Executing /usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Scripts/create_tunnel.sh 192.168.1.125 192.168.1.124 mn_tun0 0
INFO:MaxiNet.WorkerServer.server:Creating mininet instance
ERROR:MaxiNet.WorkerServer.server:Failed to create mininet instance: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/WorkerServer/server.py", line 306, in create_mininet switch=switch, controller=controller)
  File "/home/kalcla/containernet/mininet/net.py", line 181, in __init__
    self.build()
  File "/home/kalcla/containernet/mininet/net.py", line 520, in build
    self.buildFromTopo( self.topo )
  File "/home/kalcla/containernet/mininet/net.py", line 501, in buildFromTopo
    self.addSwitch( switchName, **params )
  File "/home/kalcla/containernet/mininet/net.py", line 277, in addSwitch
    sw = cls( name, **defaults )
  File "/home/kalcla/containernet/mininet/node.py", line 1374, in __init__
    Switch.__init__( self, name, **kwargs )
  File "/home/kalcla/containernet/mininet/node.py", line 1303, in __init__
    self.dpid = self.defaultDpid( dpid )
  File "/home/kalcla/containernet/mininet/node.py", line 1314, in defaultDpid
    assert len( dpid ) <= self.dpidLen and int( dpid, 16 ) >= 0
AssertionError
DEBUG:MaxiNet.WorkerServer.server:Executing /usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Scripts/delete_tunnels.sh

Script
> kalcla@wubuntu01:~/MaxiNet/MaxiNet/Frontend/examples$ sudo python static_mapping.py 
localhost SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
no hostkey alg
localhost SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
192.168.1.125 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
192.168.1.125 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
no hostkey alg
INFO:MaxiNet.Frontend.maxinet:added worker wubuntu02
192.168.1.124 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
no hostkey alg
192.168.1.124 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
INFO:MaxiNet.Frontend.maxinet:added worker wubuntu01
INFO:MaxiNet.Frontend.maxinet:Clustering topology...
DEBUG:MaxiNet.Frontend.partitioner:metis file: /tmp/fileD1Fgkv
DEBUG:MaxiNet.Frontend.partitioner:7 6 011 0
2 5 10
2 5 10
2 6 10
2 6 10
1 2 10 1 10 7 20
1 7 20 4 10 3 10
1 6 20 5 20
{'h2': 0, 'h3': 1, 'h1': 0, 'h4': 1, 's3': 1, 's2': 0, 's1': 0, 's7': 1, 's6': 1, 's5': 0, 's4': 1}
DEBUG:MaxiNet.Frontend.partitioner:Topologies:
DEBUG:MaxiNet.Frontend.partitioner:Partition 0
DEBUG:MaxiNet.Frontend.partitioner:Nodes: ['h1', 'h2', 's1', 's2', 's5']
DEBUG:MaxiNet.Frontend.partitioner:Links: [('h2', 's2'), ('s2', 's5'), ('s1', 's5'), ('h1', 's1')]
DEBUG:MaxiNet.Frontend.partitioner:Partition 1
DEBUG:MaxiNet.Frontend.partitioner:Nodes: ['h3', 'h4', 's3', 's4', 's6', 's7']
DEBUG:MaxiNet.Frontend.partitioner:Links: [('s3', 's6'), ('h3', 's3'), ('s6', 's7'), ('h4', 's4'), ('s4', 's6')]
DEBUG:MaxiNet.Frontend.partitioner:Tunnels: [['s5', 's7', {'delay': '0.1ms', 'bw': 20.0, 'node1': 's5', 'node2': 's7', 'port2': 1, 'port1': 3}]]
DEBUG:MaxiNet.Frontend.maxinet:Tunnels: [['s5', 's7', {'delay': '0.1ms', 'bw': 20.0, 'node1': 's5', 'node2': 's7', 'port2': 1, 'port1': 3}]]
DEBUG:MaxiNet.Frontend.maxinet:invoking tunnel create commands on 192.168.1.125 and 192.168.1.124
DEBUG:MaxiNet.Frontend.maxinet:tunnel mn_tun0 created.
Traceback (most recent call last):
  File "static_mapping.py", line 30, in <module>
    exp.setup()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 1466, in setup
    controller=self.controller)
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 201, in start
    switch=self.switch, STT=STT)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 476, in _pyroInvoke
    raise data  # if you see this in your traceback, you should probably inspect the remote traceback as well
AssertionError
INFO:MaxiNet.Frontend.maxinet:removed worker wubuntu02
INFO:MaxiNet.Frontend.maxinet:removed worker wubuntu01

MaxiNet.cfg

>[all]
password = HalloWelt
controller = 192.168.1.124:6633
logLevel = DEBUG
port_ns = 9090
port_sshd = 5345
runWith1500MTU = True
useMultipleIPs = 0
deactivateTSO = True
sshuser = kalcla
usesudo = True
useSTT = False
[FrontendServer]
ip = 192.168.1.124
threadpool = 256
[wubuntu01]
ip = 192.168.1.124
share = 1
[wubuntu02]
ip = 192.168.1.125
share = 1

I also tried Ubuntu 16.04 but I have the same problems
Thank you

**Comment by wallaschek** [comment]
Hi kalcla,

your Problem seems to be related to the dpid issue which was fixed in 0be59029a4141d51f4f6e670664884c9cbbfcf31. Please update your Maxinet installation to the latest commit of the git repository (git pull && git checkout master && sudo make install) and try again.

Regards,
Felix

**Comment by kalcla** [comment]
thank you Felix,
but with the old file of tools.py, it all works
![immagine](https://user-images.githubusercontent.com/33467944/39430416-11fc78be-4c8e-11e8-8111-446477937990.png)
I have the mininet version: 2.3.0d1

This is the screenshot

![immagine](https://user-images.githubusercontent.com/33467944/39430463-2fe46206-4c8e-11e8-8f8f-c281832ecb1b.png)

**Comment by wallaschek** [comment]
Your filetransfer issue might be related to missing permissions on the file system or similar issues. Hard to tell without logfiles. Same goes for the openflow13 issue, probably your controller is not able to handle openflow 1.3.
I am going to close this thread as it is not related to the original issue anymore. Please open separate issues for new/other issues.

**Comment by diegomat** [comment]
> MaxiNet1.2 runs normally on a single machine, but runs error on multiple machines.I'm not sure whether the installation is wrong or the configuration is wrong.
> I installed MaxiNet1.2 on the mininet2.2.1 vm provided by mininet Official website. No errors were found during installation.I am running the frontendserver and the worker on one vm. And simplePing.py programs can be run successfully.However when I used two vm ,one(maxinet10) used as "frontendserver", another(maxinet11) used as "work", simplePing.py programs can be run successfully
> I have two VM where I am running the fronendserver and the worker.The following errors occurred when the program was running:
> mininet@maxinet11:~$ /usr/local/share/MaxiNet/examples/simplePing.py
> 
> localhost SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
> localhost SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
> 
> ```
> no hostkey alg
> Traceback (most recent call last):
>   File "/usr/local/share/MaxiNet/examples/simplePing.py", line 14, in <module>
>     cluster = maxinet.Cluster()
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 611, in __init__
>     self.add_workers()
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 705, in add_workers
>     while self.add_worker():
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 690, in add_worker
>     if(self.add_worker_by_hostname(hn)):
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 669, in add_worker_by_hostname
>     self.worker.append(Worker(self.nameserver, pyname, self.config.get_nameserver_password(), self.sshtool))
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 136, in __init__
>     self._fix_mtus()
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 344, in _fix_mtus
>     self.run_cmd("ip li se dev " + intf + " mtu 1600")
>   File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 271, in run_cmd
>     return self.server.check_output(cmd)
>   File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 187, in __call__
>     return self.__send(self.__name, args, kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 463, in _pyroInvoke
>     data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
>   File "/usr/local/lib/python2.7/dist-packages/Pyro4/util.py", line 170, in deserializeData
>     return self.loads(data)
>   File "/usr/local/lib/python2.7/dist-packages/Pyro4/util.py", line 451, in loads
>     return pickle.loads(data)
> TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())
> ```
> 
> ```
> mininet@maxinet11:~$ 
> ==============================
> Last login: Wed Nov 22 06:36:26 2017
> mininet@maxinet10:~$  MaxiNetFrontendServer
> Broadcast server running on 0.0.0.0:9091
> NS running on 192.168.10.10:9090 (192.168.10.10)
> URI = PYRO:Pyro.NameServer@192.168.10.10:9090
> Monitoring clusters...
> INFO:MaxiNet.FrontendServer.server:startup successful. Waiting for workers to register...
> INFO:MaxiNet.FrontendServer.server:new worker signed in: maxinet11 (pyro: MaxiNetWorker_maxinet11)
> INFO:MaxiNet.FrontendServer.server:reserved worker maxinet11 for id maxinet11:/usr/local/share/MaxiNet/examples/simplePing.py
> WARNING:MaxiNet.FrontendServer.server:Detected a hung cluster. Freeing workers.
> INFO:MaxiNet.FrontendServer.server:worker maxinet11 was freed
> INFO:MaxiNet.FrontendServer.server:reserved worker maxinet11 for id maxinet11:/usr/local/share/MaxiNet/examples/simplePing.py
> WARNING:MaxiNet.FrontendServer.server:Detected a hung cluster. Freeing workers.
> INFO:MaxiNet.FrontendServer.server:worker maxinet11 was freed
> =====================================================================
> mininet@maxinet11:~$  sudo MaxiNetWorker
> INFO:MaxiNet.WorkerServer.server:starting up and connecting to  192.168.10.10:9090
> INFO:MaxiNet.WorkerServer.server:configuring and starting ssh daemon...
> INFO:MaxiNet.WorkerServer.server:looking for manager application...
> INFO:MaxiNet.WorkerServer.server:signing in...
> INFO:MaxiNet.WorkerServer.server:done. Entering requestloop.
> ===============================================================
> ```
> 
> My MaxiNet.cfg file reads as follows:
> 
> ```
> ; place this at ~/.MaxiNet.cfg
> [all]
> password = HalloWelt
> controller = 192.168.10.1.1:6633
> logLevel = INFO        ; Either CRITICAL, ERROR, WARNING, INFO  or DEBUG
> port_ns = 9090         ; Nameserver port
> port_sshd = 5345       ; Port where MaxiNet will start an ssh server on each worker
> runWith1500MTU = False ; Set this to True if your physical network can not handle MTUs >1500.
> useMultipleIPs = 0     ; for RSS load balancing. Set to n > 0 to use multiple IP addresses per worker. More information on this feature can be found at MaxiNets github Wiki.
> deactivateTSO = True   ; Deactivate TCP-Segmentation-Offloading at the emulated hosts.
> sshuser = mininet         ; On Debian set this to root. On ubuntu set this to user which can do passwordless sudo
> usesudo = True        ; If sshuser is set to something different than root set this to True.
> useSTT = False         ; enables stt usage for tunnels. Only usable with OpenVSwitch. Bandwithlimitations etc do not work on STT tunnels!
> 
> [FrontendServer]
> ip = 192.168.10.10
> threadpool = 256       ; increase if more workers are needed (each Worker requires 2 threads on the FrontendServer)
> 
> [maxinet11]
> ip = 192.168.10.11
> share = 1
> ```

Hello, Did you solve this problem? I am installing the Maxinet and it is with the same problem.

**Comment by kalcla** [comment]
Sorry for my late

Have you solved the issue?

Claudio
