### ISSUE TITLE
how to use maxinet?

### ISSUE THREAD

**Issue by yyqdh** [MaxiNet/MaxiNet#36]
I had successfully installed  maxinet,But MAXINET does not provide relevant help documents. How to use in MAXINET CLI？In addition ,Can the mininet CLI command be used in maxiNET？If maixnet can, then how to get into mininet CLI？

**Comment by wette** [comment]
Take a look at the examples folder.
More specific, the example found here: https://github.com/MaxiNet/MaxiNet/blob/master/MaxiNet/Frontend/examples/shell.py
after running it (`python shell.py`), you will find yourself in the maxinet command line interface. Here, you can type `help` to get information about all build-in commands.
