### ISSUE TITLE
dynamicTopology.py does not run from pre-configured VM

### ISSUE THREAD

**Issue by AndreasPadelopoulos** [MaxiNet/MaxiNet#8]
Hello, we found a bug in your project.

Specifically, in maxinet.py under Frontend in line 733 and 734 where it sets the mtu there is a reference in a None object.

This happents because you invoke the method with node1 and node2 and after that you invoke self.get(node1). You should invoke the method with the actual strings of the nodes.

Cheers

**Comment by wallaschek** [comment]
Yep, you're right. Thank you for reporting!

**Comment by wallaschek** [comment]
Issue closed with commit 283c928f4cca0c9a78cd66022f9cec1e2d2e1413.
VMs will be fixed in upcoming release.
