### ISSUE TITLE
"wid" on switch add does not work as expected

### ISSUE THREAD

**Issue by AndreasPadelopoulos** [MaxiNet/MaxiNet#9]
Hello again,

I would expect that when I add a switch and specify that the wid = 2, that this switch would be added in the worker2, wid=3 at worker3 etc.

It seems to me that this is not the case. The mapping from workers to actual nodes does not work this way. Either way, it distributed the switches, but it should be cool to have this functionality also. I delved into the code but did not found the bug so far. Maybe you can help.

Andreas Pantelopoulos

**Comment by wallaschek** [comment]
Hi!
At which point did you add the switch? When creating the topology before starting the experiment or did you add the switch at runtime using Experiment.addSwitch? The wid argument is only supported in the latter one. If you want to map the switches beforehand you'll need to pass a mapping dict to the Experiment constructor (see nodemapping argument).

**Comment by AndreasPadelopoulos** [comment]
Ok, I will investigate it further and let you know.

Basically, what I am trying to achieve, is connect 3000+ more switches into our controller (opendaylight) and through rest-apis provided by the controller investigate whether the switches are up and connected.

Is there any way to determine whether MaxiNet has succesfully created the topology of switches or not?

Andreas

**Comment by wallaschek** [comment]
In general MaxiNet should not fail in creating a topology, however the individual mininet instances might fail to spawn all processes if resources on that worker are scarce. If you use the userspace switch implementation you could iterate over all workers and (for example) parse the output of Worker.run_cmd("ps aux | grep ofdatapath") to check whether all processes are running. If you are using Openvswitch there is a ovs command to check for started switches which you could run on all Workers.  

I'm going to close the issue for now, if you find that you were using Experiment.addSwitch and the wid argument was not respected please give a notice and I'll reopen it. For general questions about MaxiNet feel free to join our mailinglist at https://lists.uni-paderborn.de/mailman/listinfo/maxinet 

Regards,
Felix

**Comment by ChaitanyaKr** [comment]
Here's an issue I face with Experiment.addSwitch(). 
Say I have a topology that requires only 5 switches (so, maxWorkers = minWorkers = 5), but I have 10 or so workers signed into the FrontEnd. I observe that in this scenario, my mapping of switches to wid is not respected. Any particular reason why this would be happening? (I'm using MaxiNet v1.0)
-Chaitanya
